### ISSUE TITLE
The OpenFAST executables (and other drivers) do not include the git version information

### ISSUE THREAD

**Issue by andrew-platt** [conda-forge/openfast-feedstock#25]
### Comment:

The `meta.yaml` specifies downloading the tarball of a release from the OpenFAST repository.  During the OpenFAST build process, there is no git version information available for cmake so the version info doesn't get set.  Since this info is added to all output files, this makes it a bit more difficult to check which conda installed version of OpenFAST was used on an old simulation result.

There is probably a way to pass the `sha256` git information and package name and version from the `meta.yaml` setup process, but this may take some work to implement (potentially also requiring modifications to the OpenFAST build process with new environment variables).

The dev version of OpenFAST from conda does include version info from the git tag, though it appears to not pick up the latest tag (I have a very vague recollection of different tag types potentially being an issue).

NOTE: this is not really a question, but more of an issue for us to resolve at some point when time permits.

**Comment by deslaughter** [comment]
Resolved by PR #39 which switched to using git to download the repo before building instead of just the archive file.
